name: Docker Build and Push

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 * * 0"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  docker:
    name: Docker Build and Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      ## Setup environment variables
      - name: Set branch name as Docker image tag
        shell: bash
        run: echo "TAG_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

      - name: Replace master or main branch with latest tag
        if: env.TAG_NAME == 'main' || env.TAG_NAME == 'master'
        shell: bash
        run: echo "TAG_NAME=latest" >> $GITHUB_ENV

      - name: Set tag to release name if release event
        if: github.event_name == 'release'
        shell: bash
        run: echo "TAG_NAME=$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_ENV

      - name: Store repo name and owner in lower case
        shell: bash
        run: echo "LOWER_CASE_REPO_NAME=$(echo ${GITHUB_REPOSITORY} | tr /A-Z/ /a-z/)" >> $GITHUB_ENV

      ## Configure, build and push docker image
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker QEMU
        uses: docker/setup-qemu-action@v2

      - name: Login to Docker registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4.0.0
        with:
          platforms: linux/arm64/v8
          context: ./root-container
          # Only releases or pushes to development or main branch
          push: ${{ github.event_name == 'release' || env.TAG_NAME == 'development' || env.TAG_NAME == 'latest' }}
          tags: ghcr.io/${{ env.LOWER_CASE_REPO_NAME }}:${{ env.TAG_NAME }}
          # Use GitHub Actions cache
          cache-from: type=gha
          cache-to: type=gha,mode=max
